//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTravelHistory
    {
        public int travel_ID { get; set; }
        public Nullable<int> employee_ID { get; set; }
        public Nullable<int> subsidiary_ID { get; set; }
        public Nullable<int> transporter_ID { get; set; }
        public Nullable<System.DateTime> departure_Date_and_Time { get; set; }
        public Nullable<decimal> distance_Kilometers { get; set; }
        public Nullable<decimal> travel_Cost { get; set; }
    
        public virtual tbEmployee tbEmployee { get; set; }
        public virtual tbSubsidiary tbSubsidiary { get; set; }
        public virtual tbTransporter tbTransporter { get; set; }
    }
}
