//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_GMEDINAEntities1 : DbContext
    {
        public ERP_GMEDINAEntities1()
            : base("name=ERP_GMEDINAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAccesoRol> tbAccesoRols { get; set; }
        public virtual DbSet<tbBitacoraErrore> tbBitacoraErrores { get; set; }
        public virtual DbSet<tbObjeto> tbObjetoes { get; set; }
        public virtual DbSet<tbRol> tbRols { get; set; }
        public virtual DbSet<tbRolesUsuario> tbRolesUsuarios { get; set; }
        public virtual DbSet<tbUsuario> tbUsuarios { get; set; }
    }
}
